---
title: "Spring Cleaning: Variable Star Validation"
author: "David J Jackson"
date: "3/15/2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE,message =FALSE)
knitr::opts_chunk$set(fig.width=8, fig.height=6)
library(tidyverse)
library(plotly)
library(insol)
library(forecast)
library(DT)
library(data.table)
library(ggeasy)
library(LC)
library(lubridate)

```

### Variable Star: RT_Cyg 

```{r, echo=FALSE}
rm(list=ls())
mydata <-read_csv("./RT_Cyg.csv",
                  col_types=cols(JD=col_double(),
                                 Magnitude=col_number())) 

mydata$jd <- as.integer(mydata$JD)
mydata$Ymd <- JD(mydata$jd,inverse = TRUE)
mydata$Ymd <- as.Date(mydata$Ymd)
summary(mydata)

```

```{r}

weekavg <- mydata %>% group_by(weekly = floor_date(Ymd,"week")) %>% 
  summarise(weekly_magnitude = mean(Magnitude)) %>%
  mutate(Dimmer = weekly_magnitude +1) %>%
  mutate(Brighter = weekly_magnitude -1)

dailyavg <- mydata %>% group_by(Julian = jd) %>% 
  summarise(daily_magnitude = mean(Magnitude)) %>%
  mutate(Dimmer = daily_magnitude +1) %>%
  mutate(Brighter = daily_magnitude -1)
```

```{r}

ggplot(weekavg,aes(x=weekly,y=weekly_magnitude)) + geom_point() +
  easy_rotate_x_labels(angle=45) + scale_y_reverse() +
  labs(title="Weekly Mean Magnitude")

ggplot(dailyavg,aes(x=Julian,y=daily_magnitude)) + geom_line() +
  easy_rotate_x_labels(angle=180) + scale_y_reverse() + 
    labs(title="Daily Mean")
  
```

```{r}
#dailyavg$Julian  <- JD(dailyavg$Daily)

ggplot(data=mydata,aes(x=jd,y=Magnitude,col="Magnitude")) + geom_point() +
   labs(title="Daily Mean by Julian Date",x="Julian Date",y="Mean Magnitude") + 
  geom_line(data=dailyavg,aes(x=Julian,y=Brighter,col="Brighter")) +
  geom_line(data=dailyavg,aes(x=Julian,y=Dimmer,col="Dimmer")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 0)) +
   scale_y_reverse()
```



  
  
  
  
  
  
  
  
  
  

