---
title: "Sprint Cleaning: Variable Star Validation"
author: "David J Jackson"
date: "3/15/2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.width=8, fig.height=6)
library(tidyverse)
library(plotly)
library(insol)
library(forecast)
library(DT)
library(data.table)
```

### Variable Star: R_HYA (Jan. 2014 - Mar. 2020)



```{r, echo=FALSE}
rm(list=ls())
mydata <-data.table::fread("../db/R_Hya.csv") %>% 
  select(JD,Star_Name,Band,Magnitude,Validation_Flag) %>%
  mutate( JD = as.numeric(JD)) %>%
  mutate(Ymd =insol::JD(JD,inverse = TRUE)) %>%
  mutate(Ymd = as.Date(Ymd))  %>%
  mutate(Magnitude = as.numeric( gsub("<","", Magnitude) ) + 0.99) %>%
    filter(Band=="Vis." )
mydata$Star_Name <- "KHI_CYG"
```

#### Basic Analysis: Star_Name,Band and Validation_Flag

```{r, echo=FALSE}
mydata$Validation_Flag <-ifelse(mydata$Validation_Flag=="U","Not VAlidated",mydata$Validation_Flag)
mydata$Validation_Flag <-ifelse(mydata$Validation_Flag=="Z","pre-validation",mydata$Validation_Flag)
mydata$Validation_Flag <-ifelse(mydata$Validation_Flag=="V","Validated",mydata$Validation_Flag)
mydata$Validation_Flag <-ifelse(mydata$Validation_Flag=="T","Failed",mydata$Validation_Flag)

mydata %>% group_by(Star_Name) %>% summarise(Count = n())
mydata %>% group_by(Band) %>% summarise(Count = n())
mydata %>% group_by(Validation_Flag) %>% summarise(Count = n())
```


```{r, echo=FALSE}
plot_ly(mydata,x=~Ymd,y=~Magnitude,type="scatter",mode="markers",symbol=~Validation_Flag,colors="Set1") %>%
  layout(yaxis = list(autorange = "reversed")) %>%
  layout(title = "Plot of Observation by Validation Flags")
 
```

#### Using Daily Means to Validate Variable Stars

```{r, echo=FALSE}
starDust <- mydata %>%
    group_by(Ymd) %>%
    summarize(Mean = round(mean(Magnitude),digits=1),
              Brighter = round(Mean -1,digits = 1),
              Fainter = round(Mean +1,digits= 1),
              Obs = n()) %>% 
    ungroup() %>% 
    mutate(Verify = case_when(
      (Brighter <  Mean -1) | (Fainter > Mean + 1) ~ "Yes",TRUE ~ "No")) %>%
      filter(Obs >=3 & Verify=="Yes") 

```
```{r, echo=FALSE}
mydata %>% plot_ly(x=~Ymd,y=~Magnitude,name="Magnitude",type="scatter",mode="markers") %>% 
  add_lines(data=starDust,x=~Ymd,y=~Fainter,name="Mean +1") %>% 
  add_lines(data=starDust,x=~Ymd,y=~Brighter,name="Mean -1") %>%
   layout(yaxis = list(autorange = "reversed")) %>%
  layout(title = "Daily Means +/- 1")
```
```{r}
starDust %>% DT::datatable()
```


#### Validation Using (3 DAy) Moving Averages

```{r, echo=FALSE}
mydata$MA <- forecast::ma(mydata$Magnitude,order=3)
mydata$MA <- round(mydata$MA,digits = 1)
mydata$Plus <- round(mydata$MA +1,digits = 1)
mydata$Minus <- round(mydata$MA -1,digits= 1)

mydata %>% plot_ly(x=~Ymd,y=~Magnitude,name="Magnitude",type="scatter",mode="markers") %>% 
  add_lines(x=~Ymd,y=~Plus,name="Mean +1") %>% 
  add_lines(x=~Ymd,y=~Minus,name="Mean -1.") %>%
   layout(yaxis = list(autorange = "reversed")) %>%
    layout(title = "3 Day Moving +/- 1")

```
